#!/bin/bash
text=`t | dmenu -i -t -l 10`

[ -z "$text" ] && exit 0

id=`echo "$text" | grep -Po '^[a-z0-9]+(?= +-)'`
action=`[ ! -z "$id" ] && echo "$text" | grep -Po '\s(EE|DD)$'`

[ -z "$id" ] && t "$text"
[ ! -z "$id" ] && [ -z "$action" ] && t -f "$id"
[ "$action" = ' EE' ] && t -e "$id" `echo $text | sed -r "s/^\w+ +- +(.+) EE$/\1/"`
[ "$action" = ' DD' ] && t -r "$id"
